sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t richardbmk/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true richardbmk/react-test npm test

after_success:
  - docker build -t richardbmk/client ./client
  - docker build -t richardbmk/nginx ./nginx
  - docker build -t richardbmk/server ./server
  - docker build -t richardbmk/worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin docker.io
  # Take those images and push them to docker hub
  - docker push richardbmk/client
  - docker push richardbmk/nginx
  - docker push richardbmk/server
  - docker push richardbmk/worker

